-- AlterTable
ALTER TABLE "ContaUsuario" ALTER COLUMN "usuario" SET DATA TYPE TEXT,
ALTER COLUMN "senha" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Receita" ALTER COLUMN "nome" SET DATA TYPE TEXT,
ALTER COLUMN "ingredientes" SET DATA TYPE TEXT,
ALTER COLUMN "comoFazer" SET DATA TYPE TEXT;
